parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: symfony
    database_user: root
    database_password: 
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 
    database_path: null
    fina_wsdl: http://localhost/pro3x/fina-1-2/wsdl/FiskalizacijaService.wsdl
    daily_report: Pro3xInvoiceBundle:Report:printDailyReport.html.twig
    logo_url: 
    company_info: 
