pro3x_warehouse:
    resource: "@Pro3xWarehouseBundle/Controller/"
    type:     annotation
    prefix:   /

pro3x_registration_keys:
    resource: "@Pro3xRegistrationKeysBundle/Controller/"
    type:     annotation
    prefix:   /

pro3x_invoice:
    resource: "@Pro3xInvoiceBundle/Controller/"
    type:     annotation
    prefix:   /

pro3x_app:
    resource: "@Pro3xAppBundle/Controller/"
    type:     annotation
    prefix:   /

pro3x_security:
    resource: "@Pro3xSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

home:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: dashboard
        permanent: true
    
#_demo_secured:
#    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
#    type:     annotation

  
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
