pro3x_invoice:
    resource: "@Pro3xInvoiceBundle/Controller/"
    type:     annotation
    prefix:   /

pro3x_app:
    resource: "@Pro3xAppBundle/Controller/"
    type:     annotation
    prefix:   /

pro3x_security:
    resource: "@Pro3xSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

home:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }
    
_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

  
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
